backend:
  name: github
  repo: swellander/bkmusic

media_folder: static/assets
public_folder: assets

collections:
  - name: gigs
    label: Gigs
    folder: gigs
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: address, label: Address }
      - { name: link, label: Event Link }
      - { name: description, label: Description, widget: markdown }
      